-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: SivugVehashlama/db/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/sivugvehashlama_pages (
  sv_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  sv_page_id INTEGER UNSIGNED NOT NULL,
  sv_complex SMALLINT UNSIGNED NOT NULL
);

CREATE UNIQUE INDEX sv_id ON /*_*/sivugvehashlama_pages (sv_id);

CREATE UNIQUE INDEX sv_page_id ON /*_*/sivugvehashlama_pages (sv_page_id);
