-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: SivugVehashlama/db/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/sivugvehashlama_pages (
  sv_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  sv_page_id INT UNSIGNED NOT NULL,
  sv_complex TINYINT UNSIGNED NOT NULL,
  UNIQUE INDEX sv_id (sv_id),
  UNIQUE INDEX sv_page_id (sv_page_id),
  PRIMARY KEY(sv_id)
) /*$wgDBTableOptions*/;
