-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: SivugVehashlama/db/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE sivugvehashlama_pages (
  sv_id SERIAL NOT NULL,
  sv_page_id INT NOT NULL,
  sv_complex SMALLINT NOT NULL,
  PRIMARY KEY(sv_id)
);

CREATE UNIQUE INDEX sv_id ON sivugvehashlama_pages (sv_id);

CREATE UNIQUE INDEX sv_page_id ON sivugvehashlama_pages (sv_page_id);
